### ISSUE TITLE
setup.py refers to file not available in PyPi package

### ISSUE THREAD

**Issue by PureTryOut** [dralshehri/hijri-converter#3]
The `setup.py` script refers to CHANGELOG.rst which doesn't exist in the PyPi package, and the installation fails because of it. To fix it, please submit a new version to PyPi including the CHANGELOG.rst. I would prefer if tests were also included.

**Comment by dralshehri** [comment]
I will add a `MANIFEST.in` file to include `CHANGELOG.rst` and `tests` within the built package on PyPI.
Thanks for reporting this issue.

**Comment by dralshehri** [comment]
A new release (v2.1.1) has been published to PyPI fixing this issue. Thanks again!
